version: "3.9"
services:
  db:
    image: "postgres:${POSTGRES_VERSION:-latest}"
    restart: "always"
    container_name: "idp_postgres"
    environment:
      POSTGRES_DB: "IdentityPortal"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 54320:5432
    volumes:
      - idp_data:/var/lib/postgresql/data
volumes:
  idp_data: