version: "3.9"
services:
  db:
    image: "postgres:${POSTGRES_VERSION:-latest}"
    restart: "always"
    container_name: "idp_postgres"
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - 54320:5432
    volumes:
      - idp_data:/mvar/lib/postgresql/data
volumes:
  idp_data: 